### ISSUE TITLE
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

### ISSUE THREAD

**Issue by limaodaxia** [jayliu0313/Shape-Guided#11]
>Traceback (most recent call last):
  File "/private/Shape-Guided-main/main.py", line 92, in <module>
    patchcore.align()
  File "/private/Shape-Guided-main/core/shape_guide_core.py", line 111, in align
    self.methods.predict_align_data(sample, align_data_id)
  File "/private/Shape-Guided-main/core/rgb_sdf_feature.py", line 163, in predict_align_data
    rgb_map, rgb_s = self.Dict_compute_rgb_map(rgb_features_size28, rgb_features_indices, lib_idices, mode='alignment')
  File "/private/Shape-Guided-main/core/features.py", line 118, in Dict_compute_rgb_map
    knn_features =  shape_guide_rgb_features_28[knn_idx[patch]]
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

how to solve this problem?

**Comment by jayliu0313** [comment]
It is recommended to use GPU to test, or you can change all the tensor device to "cpu".
