### ISSUE TITLE
An OS bug is reported when I tried to run the main.py

### ISSUE THREAD

**Issue by wentaoxie7** [jayliu0313/Shape-Guided#2]
I follow your instruction on data preprocessing and cut_paste, but when I run the main part, there seems to be an unexpected error that I encounter. Here is the error description, could you help me to fix it?

```
SDF Device: cuda
sdf device cuda

Running on class bagel

Extracting train features for class bagel:   0%|          | 0/244 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/wt/miniconda3/envs/shape_guide/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
  File "/home/wt/miniconda3/envs/shape_guide/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
  File "/home/wt/miniconda3/envs/shape_guide/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 348, in reduce_storage
  File "/home/wt/miniconda3/envs/shape_guide/lib/python3.8/multiprocessing/reduction.py", line 198, in DupFd
  File "/home/wt/miniconda3/envs/shape_guide/lib/python3.8/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
```

**Comment by jayliu0313** [comment]
Yes. If you are the Linux user, maybe you can try to use the command "ulimit -n 4096",which can increase the limit on the number of open file.

**Comment by jayliu0313** [comment]
I am not sure, but you have the same issue with the OS error?
Perhaps some issues can be resolved by modifying the code. You can search online for relevant troubleshooting related to the OS.

**Comment by wentaoxie7** [comment]
> Yes. If you are the Linux user, maybe you can try to use the command "ulimit -n 4096",which can increase the limit on the number of open file. You can refer this link "https://support.posit.co/hc/en-us/articles/10528138427031-ERROR-system-error-24-Too-many-open-files-on-Posit-Workbench".

Problem solved! thanks!
